build: deploy test v1.4

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -23,14 +23,18 @@ jobs:
         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
     - name: Build and push Docker image
+      id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         push: true
         tags: guilherm124/navgo-api:latest
 
-    - name: List Docker images (Debug)
-      run: docker images
+    - name: Debug Docker build output
+      run: |
+        echo "Docker Build Output"
+        docker images
+        docker image inspect guilherm124/navgo-api:latest || echo "Image not found"
 
     - name: Verify Docker image exists
       run: |
