build: deploy test v1.2

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -29,6 +29,14 @@ jobs:
         push: true
         tags: guilherm124/navgo-api:latest
 
+    - name: Verify Docker image exists
+      run: |
+        docker images
+        if ! docker images guilherm124/navgo-api:latest | grep -q 'latest'; then
+          echo "Docker image guilherm124/navgo-api:latest not found"
+          exit 1
+        fi
+
     - name: Set up Google Cloud SDK
       uses: google-github-actions/setup-gcloud@v1
       with:
